---
- name: Install dovecot
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-pop3d

- name: Configure dovecot
  template:
    src: dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf

- name: Make sure dovecot is started
  service:
    name: dovecot
    state: started
